[features]
seeds = false
skip-lint = false
[programs.localnet]
crowd_funding = "26Po2VeZAm4vzQwvh1NXruo1U2s1zqBdiBvxeoqjxSxU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
